// Code generated by ogen, DO NOT EDIT.

package v1

import (
	"net/http"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// GetStatsParams is parameters of get_stats operation.
type GetStatsParams struct {
	ScopeID string
	Period  OptStatsPeriod `json:",omitempty,omitzero"`
}

func unpackGetStatsParams(packed middleware.Parameters) (params GetStatsParams) {
	{
		key := middleware.ParameterKey{
			Name: "scope_id",
			In:   "query",
		}
		params.ScopeID = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "period",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Period = v.(OptStatsPeriod)
		}
	}
	return params
}

func decodeGetStatsParams(args [0]string, argsEscaped bool, r *http.Request) (params GetStatsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: scope_id.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "scope_id",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ScopeID = c
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     1,
					MinLengthSet:  true,
					MaxLength:     256,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         regexMap[".*\\S.*"],
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.ScopeID)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "scope_id",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: period.
	{
		val := StatsPeriod("30d")
		params.Period.SetTo(val)
	}
	// Decode query: period.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "period",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotPeriodVal StatsPeriod
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotPeriodVal = StatsPeriod(c)
					return nil
				}(); err != nil {
					return err
				}
				params.Period.SetTo(paramsDotPeriodVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Period.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "period",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
