// Code generated by tools/api-generate; DO NOT EDIT.

package v1

const maxCombinedCandidateEvidence = 32

// CombinedEvidenceLimitError reports the PowerContext Candidate constraint
// that source_refs and artifact_refs share one maximum. OpenAPI 3.0 can
// describe each array limit but cannot express their combined cardinality.
type CombinedEvidenceLimitError struct {
	SourceReferences   int
	ArtifactReferences int
}

func (*CombinedEvidenceLimitError) Error() string {
	return "source_refs and artifact_refs together must not exceed 32 references"
}

// ValidatePowerContextContract applies semantic constraints that the frozen
// OpenAPI 3.0 document describes but cannot encode as schema keywords.
func ValidatePowerContextContract(value any) error {
	switch value := value.(type) {
	case ArtifactCandidate:
		return validateCombinedCandidateEvidence(len(value.SourceRefs), len(value.ArtifactRefs))
	case *ArtifactCandidate:
		if value == nil {
			return nil
		}
		return validateCombinedCandidateEvidence(len(value.SourceRefs), len(value.ArtifactRefs))
	case GenerateExperienceRequest:
		return validateCombinedCandidateEvidence(len(value.SourceRefs), len(value.ArtifactRefs))
	case *GenerateExperienceRequest:
		if value == nil {
			return nil
		}
		return validateCombinedCandidateEvidence(len(value.SourceRefs), len(value.ArtifactRefs))
	case GenerateSkillRequest:
		return validateCombinedCandidateEvidence(len(value.SourceRefs), len(value.ArtifactRefs))
	case *GenerateSkillRequest:
		if value == nil {
			return nil
		}
		return validateCombinedCandidateEvidence(len(value.SourceRefs), len(value.ArtifactRefs))
	case ProposeExperienceRequest:
		return validateCombinedCandidateEvidence(len(value.SourceRefs), len(value.ArtifactRefs))
	case *ProposeExperienceRequest:
		if value == nil {
			return nil
		}
		return validateCombinedCandidateEvidence(len(value.SourceRefs), len(value.ArtifactRefs))
	case ProposeSkillRequest:
		return validateCombinedCandidateEvidence(len(value.SourceRefs), len(value.ArtifactRefs))
	case *ProposeSkillRequest:
		if value == nil {
			return nil
		}
		return validateCombinedCandidateEvidence(len(value.SourceRefs), len(value.ArtifactRefs))
	case ReviseArtifactCandidateRequest:
		return validateCombinedCandidateEvidence(len(value.SourceRefs), len(value.ArtifactRefs))
	case *ReviseArtifactCandidateRequest:
		if value == nil {
			return nil
		}
		return validateCombinedCandidateEvidence(len(value.SourceRefs), len(value.ArtifactRefs))
	case ArtifactCandidateHeaders:
		return ValidatePowerContextContract(value.Response)
	case *ArtifactCandidateHeaders:
		if value == nil {
			return nil
		}
		return ValidatePowerContextContract(value.Response)
	case ArtifactCandidatePage:
		return validateArtifactCandidatePageContract(value)
	case *ArtifactCandidatePage:
		if value == nil {
			return nil
		}
		return validateArtifactCandidatePageContract(*value)
	case ArtifactCandidatePageHeaders:
		return ValidatePowerContextContract(value.Response)
	case *ArtifactCandidatePageHeaders:
		if value == nil {
			return nil
		}
		return ValidatePowerContextContract(value.Response)
	case GeneratedCandidateResponse:
		return validateGeneratedCandidateResponseContract(value)
	case *GeneratedCandidateResponse:
		if value == nil {
			return nil
		}
		return validateGeneratedCandidateResponseContract(*value)
	case GeneratedCandidateResponseHeaders:
		return ValidatePowerContextContract(value.Response)
	case *GeneratedCandidateResponseHeaders:
		if value == nil {
			return nil
		}
		return ValidatePowerContextContract(value.Response)
	default:
		return nil
	}
}

func validateCombinedCandidateEvidence(sourceReferences, artifactReferences int) error {
	if sourceReferences+artifactReferences <= maxCombinedCandidateEvidence {
		return nil
	}
	return &CombinedEvidenceLimitError{
		SourceReferences: sourceReferences, ArtifactReferences: artifactReferences,
	}
}

func validateArtifactCandidatePageContract(value ArtifactCandidatePage) error {
	for index := range value.Candidates {
		if err := ValidatePowerContextContract(value.Candidates[index]); err != nil {
			return err
		}
	}
	return nil
}

func validateGeneratedCandidateResponseContract(value GeneratedCandidateResponse) error {
	candidate, ok := value.Candidate.Get()
	if !ok {
		return nil
	}
	return ValidatePowerContextContract(candidate)
}
