package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"net/http"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"strings"

	"github.com/ghodss/yaml"
)

type clientOperation struct {
	methodName    string
	path          string
	successStatus int
	requestName   string
	requestType   string
	responseType  string
}

func generateClientInvoker(specification []byte, generatedClientPath, outputPath string) error {
	operations, err := clientOperations(specification, generatedClientPath)
	if err != nil {
		return err
	}
	var output bytes.Buffer
	output.WriteString("// Code generated by tools/api-generate; DO NOT EDIT.\n\n")
	output.WriteString("package client\n\n")
	output.WriteString("import (\n\t\"context\"\n\n\tv1 \"github.com/ob-labs/powercontext-go/api/v1\"\n)\n\n")
	output.WriteString("type normalizedInvoker struct { raw v1.Invoker }\n\n")
	output.WriteString("var _ v1.Invoker = normalizedInvoker{}\n")
	for _, operation := range operations {
		fmt.Fprintf(&output, "\nfunc (i normalizedInvoker) %s(ctx context.Context", operation.methodName)
		if operation.requestName != "" {
			fmt.Fprintf(&output, ", %s %s", operation.requestName, qualifyWireType(operation.requestType))
		}
		fmt.Fprintf(&output, ") (%s, error) {\n", qualifyWireType(operation.responseType))
		if operation.requestName != "" {
			requestExpression := operation.requestName
			if !strings.HasPrefix(operation.requestType, "*") {
				requestExpression = "&" + requestExpression
			}
			fmt.Fprintf(&output, "\tif err := validateOperationRequest(%q, %s); err != nil {\n", operation.path, requestExpression)
			fmt.Fprintf(&output, "\t\tvar zero %s\n\t\treturn zero, err\n\t}\n", qualifyWireType(operation.responseType))
		}
		fmt.Fprintf(&output, "\treturn invokeOperation(ctx, operationDescriptor{path: %q, successStatus: %d}, func(ctx context.Context) (%s, error) {\n",
			operation.path, operation.successStatus, qualifyWireType(operation.responseType))
		fmt.Fprintf(&output, "\t\treturn i.raw.%s(ctx", operation.methodName)
		if operation.requestName != "" {
			fmt.Fprintf(&output, ", %s", operation.requestName)
		}
		output.WriteString(")\n\t})\n}\n")
	}
	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return fmt.Errorf("format generated Client Invoker: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		return err
	}
	return os.WriteFile(outputPath, formatted, 0o644)
}

func clientOperations(specification []byte, generatedClientPath string) ([]clientOperation, error) {
	specOperations, err := parseClientSpecOperations(specification)
	if err != nil {
		return nil, err
	}
	generated, err := os.ReadFile(generatedClientPath)
	if err != nil {
		return nil, err
	}
	methods, err := parseInvokerMethods(generated)
	if err != nil {
		return nil, err
	}
	if len(methods) != len(specOperations) {
		return nil, fmt.Errorf("Invoker has %d methods but OpenAPI has %d operations", len(methods), len(specOperations))
	}
	for index := range methods {
		operation, ok := specOperations[methods[index].methodName]
		if !ok {
			return nil, fmt.Errorf("Invoker method %s has no OpenAPI operation", methods[index].methodName)
		}
		methods[index].path = operation.path
		methods[index].successStatus = operation.successStatus
		delete(specOperations, methods[index].methodName)
	}
	if len(specOperations) != 0 {
		return nil, errors.New("OpenAPI contains operations absent from Invoker")
	}
	slices.SortFunc(methods, func(left, right clientOperation) int {
		return strings.Compare(left.methodName, right.methodName)
	})
	return methods, nil
}

func parseClientSpecOperations(specification []byte) (map[string]clientOperation, error) {
	encoded, err := yaml.YAMLToJSON(specification)
	if err != nil {
		return nil, err
	}
	var document struct {
		Paths map[string]map[string]struct {
			OperationID string                     `json:"operationId"`
			Responses   map[string]json.RawMessage `json:"responses"`
		} `json:"paths"`
	}
	if err := json.Unmarshal(encoded, &document); err != nil {
		return nil, err
	}
	result := make(map[string]clientOperation)
	for path, item := range document.Paths {
		for method, operation := range item {
			if !isHTTPMethod(method) {
				continue
			}
			if operation.OperationID == "" {
				return nil, fmt.Errorf("%s %s has no operationId", method, path)
			}
			successStatus, err := oneSuccessStatus(operation.OperationID, operation.Responses)
			if err != nil {
				return nil, err
			}
			methodName := operationMethodName(operation.OperationID)
			if _, duplicate := result[methodName]; duplicate {
				return nil, fmt.Errorf("duplicate generated method %s", methodName)
			}
			result[methodName] = clientOperation{
				methodName: methodName,
				path:       path, successStatus: successStatus,
			}
		}
	}
	if len(result) == 0 {
		return nil, errors.New("OpenAPI contains no operations")
	}
	return result, nil
}

func parseInvokerMethods(source []byte) ([]clientOperation, error) {
	file, err := parser.ParseFile(token.NewFileSet(), "oas_client_gen.go", source, 0)
	if err != nil {
		return nil, err
	}
	var invoker *ast.InterfaceType
	for _, declaration := range file.Decls {
		general, ok := declaration.(*ast.GenDecl)
		if !ok {
			continue
		}
		for _, specification := range general.Specs {
			typed, ok := specification.(*ast.TypeSpec)
			if !ok || typed.Name.Name != "Invoker" {
				continue
			}
			invoker, _ = typed.Type.(*ast.InterfaceType)
		}
	}
	if invoker == nil {
		return nil, errors.New("generated Client has no Invoker interface")
	}
	result := make([]clientOperation, 0, len(invoker.Methods.List))
	for _, field := range invoker.Methods.List {
		if len(field.Names) != 1 {
			return nil, errors.New("Invoker contains an embedded or unnamed method")
		}
		function, ok := field.Type.(*ast.FuncType)
		if !ok || function.Params == nil || function.Results == nil ||
			len(function.Params.List) < 1 || len(function.Params.List) > 2 || len(function.Results.List) != 2 {
			return nil, fmt.Errorf("unsupported Invoker signature for %s", field.Names[0].Name)
		}
		if !isContextParameter(function.Params.List[0]) || !isErrorResult(function.Results.List[1]) {
			return nil, fmt.Errorf("unsupported Invoker boundary for %s", field.Names[0].Name)
		}
		responseType, err := wireType(function.Results.List[0].Type)
		if err != nil {
			return nil, fmt.Errorf("%s response: %w", field.Names[0].Name, err)
		}
		operation := clientOperation{methodName: field.Names[0].Name, responseType: responseType}
		if len(function.Params.List) == 2 {
			parameter := function.Params.List[1]
			if len(parameter.Names) != 1 {
				return nil, fmt.Errorf("unsupported request parameter for %s", operation.methodName)
			}
			operation.requestName = parameter.Names[0].Name
			operation.requestType, err = wireType(parameter.Type)
			if err != nil {
				return nil, fmt.Errorf("%s request: %w", operation.methodName, err)
			}
			if !strings.HasPrefix(operation.requestType, "*") && operation.requestType != "GetStatsParams" {
				return nil, fmt.Errorf("unsupported value request type %s for %s", operation.requestType, operation.methodName)
			}
		}
		result = append(result, operation)
	}
	return result, nil
}

func wireType(expression ast.Expr) (string, error) {
	switch value := expression.(type) {
	case *ast.Ident:
		return value.Name, nil
	case *ast.StarExpr:
		identifier, ok := value.X.(*ast.Ident)
		if !ok {
			return "", errors.New("pointer does not target a generated type")
		}
		return "*" + identifier.Name, nil
	default:
		return "", fmt.Errorf("unsupported generated type %T", expression)
	}
}

func qualifyWireType(value string) string {
	if strings.HasPrefix(value, "*") {
		return "*v1." + strings.TrimPrefix(value, "*")
	}
	return "v1." + value
}

func isContextParameter(field *ast.Field) bool {
	if len(field.Names) != 1 || field.Names[0].Name != "ctx" {
		return false
	}
	selector, ok := field.Type.(*ast.SelectorExpr)
	if !ok {
		return false
	}
	packageName, packageOK := selector.X.(*ast.Ident)
	return packageOK && packageName.Name == "context" && selector.Sel.Name == "Context"
}

func isErrorResult(field *ast.Field) bool {
	identifier, ok := field.Type.(*ast.Ident)
	return ok && identifier.Name == "error"
}

func isHTTPMethod(value string) bool {
	switch strings.ToUpper(value) {
	case http.MethodGet, http.MethodHead, http.MethodPost, http.MethodPut, http.MethodPatch, http.MethodDelete, http.MethodOptions, http.MethodTrace:
		return true
	default:
		return false
	}
}

func oneSuccessStatus(operationID string, responses map[string]json.RawMessage) (int, error) {
	statuses := make([]int, 0, 1)
	for value := range responses {
		status, err := strconv.Atoi(value)
		if err == nil && status >= 200 && status < 300 {
			statuses = append(statuses, status)
		}
	}
	if len(statuses) != 1 {
		return 0, fmt.Errorf("operation %s has %d success statuses, want exactly one", operationID, len(statuses))
	}
	return statuses[0], nil
}

func operationMethodName(operationID string) string {
	var result strings.Builder
	for _, part := range strings.Split(operationID, "_") {
		if part == "" {
			continue
		}
		result.WriteString(strings.ToUpper(part[:1]))
		result.WriteString(part[1:])
	}
	return result.String()
}
