package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"slices"

	"github.com/ghodss/yaml"
)

const maxCombinedCandidateEvidence = 32

// generateContractValidation emits the small semantic layer that cannot be
// represented by OpenAPI 3.0. The Python generator derives the same model set
// from source_refs/artifact_refs maxItems; keeping that discovery rule here
// prevents either transport from maintaining a handwritten list.
func generateContractValidation(specification []byte, outputPath string) error {
	models, err := candidateEvidenceModels(specification)
	if err != nil {
		return err
	}
	if len(models) == 0 {
		return errors.New("OpenAPI contains no combined Candidate evidence models")
	}

	var output bytes.Buffer
	output.WriteString("// Code generated by tools/api-generate; DO NOT EDIT.\n\n")
	output.WriteString("package v1\n\n")
	fmt.Fprintf(&output, "const maxCombinedCandidateEvidence = %d\n\n", maxCombinedCandidateEvidence)
	output.WriteString(`// CombinedEvidenceLimitError reports the PowerContext Candidate constraint
// that source_refs and artifact_refs share one maximum. OpenAPI 3.0 can
// describe each array limit but cannot express their combined cardinality.
type CombinedEvidenceLimitError struct {
	SourceReferences   int
	ArtifactReferences int
}

func (*CombinedEvidenceLimitError) Error() string {
	return "source_refs and artifact_refs together must not exceed 32 references"
}

// ValidatePowerContextContract applies semantic constraints that the frozen
// OpenAPI 3.0 document describes but cannot encode as schema keywords.
func ValidatePowerContextContract(value any) error {
	switch value := value.(type) {
`)
	for _, model := range models {
		fmt.Fprintf(&output, "\tcase %s:\n", model)
		output.WriteString("\t\treturn validateCombinedCandidateEvidence(len(value.SourceRefs), len(value.ArtifactRefs))\n")
		fmt.Fprintf(&output, "\tcase *%s:\n", model)
		output.WriteString("\t\tif value == nil {\n\t\t\treturn nil\n\t\t}\n")
		output.WriteString("\t\treturn validateCombinedCandidateEvidence(len(value.SourceRefs), len(value.ArtifactRefs))\n")
	}
	output.WriteString(`	case ArtifactCandidateHeaders:
		return ValidatePowerContextContract(value.Response)
	case *ArtifactCandidateHeaders:
		if value == nil {
			return nil
		}
		return ValidatePowerContextContract(value.Response)
	case ArtifactCandidatePage:
		return validateArtifactCandidatePageContract(value)
	case *ArtifactCandidatePage:
		if value == nil {
			return nil
		}
		return validateArtifactCandidatePageContract(*value)
	case ArtifactCandidatePageHeaders:
		return ValidatePowerContextContract(value.Response)
	case *ArtifactCandidatePageHeaders:
		if value == nil {
			return nil
		}
		return ValidatePowerContextContract(value.Response)
	case GeneratedCandidateResponse:
		return validateGeneratedCandidateResponseContract(value)
	case *GeneratedCandidateResponse:
		if value == nil {
			return nil
		}
		return validateGeneratedCandidateResponseContract(*value)
	case GeneratedCandidateResponseHeaders:
		return ValidatePowerContextContract(value.Response)
	case *GeneratedCandidateResponseHeaders:
		if value == nil {
			return nil
		}
		return ValidatePowerContextContract(value.Response)
	default:
		return nil
	}
}

func validateCombinedCandidateEvidence(sourceReferences, artifactReferences int) error {
	if sourceReferences+artifactReferences <= maxCombinedCandidateEvidence {
		return nil
	}
	return &CombinedEvidenceLimitError{
		SourceReferences: sourceReferences, ArtifactReferences: artifactReferences,
	}
}

func validateArtifactCandidatePageContract(value ArtifactCandidatePage) error {
	for index := range value.Candidates {
		if err := ValidatePowerContextContract(value.Candidates[index]); err != nil {
			return err
		}
	}
	return nil
}

func validateGeneratedCandidateResponseContract(value GeneratedCandidateResponse) error {
	candidate, ok := value.Candidate.Get()
	if !ok {
		return nil
	}
	return ValidatePowerContextContract(candidate)
}
`)

	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return fmt.Errorf("format generated contract validation: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		return err
	}
	return os.WriteFile(outputPath, formatted, 0o644)
}

func candidateEvidenceModels(specification []byte) ([]string, error) {
	encoded, err := yaml.YAMLToJSON(specification)
	if err != nil {
		return nil, err
	}
	type property struct {
		MaxItems *int `json:"maxItems"`
	}
	var document struct {
		Components struct {
			Schemas map[string]struct {
				Properties map[string]property `json:"properties"`
			} `json:"schemas"`
		} `json:"components"`
	}
	if err := json.Unmarshal(encoded, &document); err != nil {
		return nil, err
	}
	models := make([]string, 0, 6)
	for name, schema := range document.Components.Schemas {
		sources, sourcesOK := schema.Properties["source_refs"]
		artifacts, artifactsOK := schema.Properties["artifact_refs"]
		if !sourcesOK || !artifactsOK || sources.MaxItems == nil || artifacts.MaxItems == nil {
			continue
		}
		if *sources.MaxItems == maxCombinedCandidateEvidence &&
			*artifacts.MaxItems == maxCombinedCandidateEvidence {
			models = append(models, name)
		}
	}
	slices.Sort(models)
	return models, nil
}
